### ISSUE TITLE
VLS can not infer used packages without meson or compile_commands

### ISSUE THREAD

**Issue by futurepaycc** [benwaffle/vala-language-server#161] opened 2020-10-11 01:44 UTC
os: manjaro
package: vala-language-server, vala-language-server-git
version: 0.48
os vala: 0.48
when load hello world test, output:
`
(vala-language-server:202256): vala-CRITICAL **: 03:06:25.390: vala_source_reference_construct: assertion '_file != NULL' failed
[Info  - 3:06:26 AM] Connection to server got closed. Server will restart.
`

**Comment by Prince781** [comment] 2020-10-11 01:50
I need more info. Can you give me the specific file(s) and/or commands you're using? I use Arch as my daily driver, so I have a hunch that this problem is caused by how VLS is handling a certain project setup, not anything to do with the Linux distribution.

**Comment by Prince781** [comment] 2020-10-11 01:52
Some more info you can provide other than the project source:

- a trace of VLS (start it with debug mode enabled in the VSCode extension)
- what version of libvala is VLS linked against

**Comment by futurepaycc** [comment] 2020-10-11 01:57
`(vala-language-server:206366): vala-CRITICAL **: 09:55:37.983: vala_source_reference_construct: assertion '_file != NULL' failed
[Info  - 9:55:38 AM] Connection to server got closed. Server will restart.
(vala-language-server:206393): vls-DEBUG: 09:55:38.792: server.vala:193: Finished constructing
(vala-language-server:206393): GLib-GIO-DEBUG: 09:55:38.801: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
(vala-language-server:206393): vls-DEBUG: 09:55:38.802: server.vala:239: [initialize] root path is /home/liunix/Documents/vala/hello1
`

link version: extra/vala 0.48.10-1 [installed]

**Comment by futurepaycc** [comment] 2020-10-11 01:59
hello world code:
`using Gtk;

int main (string[] args) {
    Gtk.init (ref args);

    var window = new Window ();
    window.title = "First GTK+ Program";
    window.border_width = 10;
    window.window_position = WindowPosition.CENTER;
    window.set_default_size (350, 70);
    window.destroy.connect (Gtk.main_quit);

    var button = new Button.with_label ("Click me!");
    button.clicked.connect (() => {
        button.label = "Thank you";
    });

    window.add (button);
    window.show_all ();

    Gtk.main ();
    return 0;
}
`

**Comment by Prince781** [comment] 2020-10-11 17:51
@futurepaycc it looks like VLS is working in the trace you sent? I don't see a crash.

**Comment by futurepaycc** [comment] 2020-10-12 02:47
ok, I'm  newbie to vala, looks vala-code/LPS donot support simple test project, after some google, I create a boilerplate work for this scenario:
[https://github.com/futurepaycc/vala_practise](url)
but I think the readme doc should improve for someone like me.

**Comment by Prince781** [comment] 2020-10-12 17:18
> looks vala-code/LSP donot support simple test project

Simple test projects work with VLS when they don't need to use external packages. VLS needs to understand the compiler arguments of your project in order to understand what `Gtk` means, otherwise, the default is to just run the compiler without any arguments. If you were compiling your example on the command-line, you would do `valac hello1.vala --pkg gtk+-3.0`, for example. Without a `meson.build` or `compile_commands.json` in the project directory containing the project information, there's no way to understand whether `Gtk` belongs to package `gtk+-3.0` or package `gtk4` or even package `gtk+-2.0`.

**Comment by futurepaycc** [comment] 2020-10-13 06:47
so what about https://github.com/GNOME/vala itemself  with autoconf?

**Comment by Prince781** [comment] 2020-10-14 02:24
@futurepaycc won't work unless you switch to the `wip/meson` branch, because VLS doesn't support autoconf (as it's quite difficult to introspect).

**Comment by Prince781** [comment] 2020-10-17 06:07
I'm closing this issue because it's not actually a bug. There are some existing ideas about enhancing VLS that would make this issue less of a problem, but that should be mentioned in a separate ticket.

**Closed by Prince781** 2020-10-17 06:07 UTC
Labels: invalid
