### ISSUE TITLE
Internal dependencies not resolved in Meson 0.55

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#149] opened 2020-09-18 12:50 UTC
**Describe the bug**
VLS doesn't see symbols from shared lib.

**Software**
OS and version (e.g. Ubuntu 20.04): Arch
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): AUR
Vala version (`valac --version`): 0.48.10

**To Reproduce**
Source code repo: https://github.com/mesonbuild/meson/tree/master/test%20cases/vala/7%20shared%20library

![image](https://user-images.githubusercontent.com/30507409/93599281-8ea15500-f9c6-11ea-91c9-543b71b4a6c3.png)

**Comment by Prince781** [comment] 2020-09-18 13:13
See if https://github.com/benwaffle/vala-language-server/issues/139 is related

**Comment by Prince781** [comment] 2020-09-18 14:07
So I take it that it is? If so, I'm closing this as it's a duplicate of #139

**Comment by gavr123456789** [comment] 2020-09-18 14:09
Yea

**Comment by Prince781** [comment] 2020-09-20 13:57
Turns out that even though this pertains to the same underlying issue (Meson 0.55 changed build dir names), it is not a duplicate because this is another case you've found that I have to fix.

**Closed** 2020-09-20 14:59 UTC
Labels: bug
